### ISSUE TITLE
crash when run build

### ISSUE THREAD

**Issue by phamminhtnl** [xioneko/neko-anime#1]
Please fix

**Comment by xioneko** [comment]
1. Check if Android Studio is up to date.
2. go to 'Settings > Build, Execution, Deployment > Build Tools > Gradle' and verify if Gradle JDK is set to JDK 17.

**Comment by phamminhtnl** [comment]
please add english language

**Comment by xioneko** [comment]
Okay, I'll think about it, but it might be a long wait.
