### ISSUE TITLE
损坏

### ISSUE THREAD

**Issue by 283590** [xioneko/neko-anime#11]
安卓6.0.0手机安装包损坏

**Comment by xioneko** [comment]
@283590 android 9.0 及以下的版本目前不支持

**Comment by 283590** [comment]
那什么时候支持

在 2023-12-26 21:27:54，Cheni ***@***.***> 写道：


@283590 android 9.0 及以下的版本目前不支持

**Comment by xioneko** [comment]
┓( ´-` )┏ 目前不打算考虑更低的版本
