### ISSUE TITLE
点开时间表，容易出现闪退，希望开发者可以修复一下

### ISSUE THREAD

**Issue by hantiaxing** [xioneko/neko-anime#14]
![Screenshot_2024-04-16-18-50-27-49_a42744233feb4be38f319c9d45b35f43.jpg](https://github.com/xioneko/neko-anime/assets/124505885/54c48551-3c19-4597-9354-7475f9f402c0)

**Comment by xioneko** [comment]
#13 也是这个问题，先试试预发布版 [0.3.0-alpha](https://github.com/xioneko/neko-anime/releases/tag/v0.3.0-alpha)

**Comment by hantiaxing** [comment]
> #13 也是这个问题，先试试预发布版 [0.3.0-alpha](https://github.com/xioneko/neko-anime/releases/tag/v0.3.0-alpha) 

OK了，已经没有闪退了
