### ISSUE TITLE
建議增設繁簡體字切換

### ISSUE THREAD

**Issue by ghost** [xioneko/neko-anime#16]
這是可以算是我一點小小的私心了（）雖然不知道做起來難不難，但是我挺希望可以切換成繁體的

「不重要的附加問題：有考慮過上google play嗎？」

**Comment by xioneko** [comment]
动漫数据源用的是简体，感觉简繁转换会比较麻烦

关于 google play，这个 app 可能还没那么正式吧，樱花动漫的视频源也不怎么好用，最主要的问题还是以后的开发和维护目前并没有定数😌

**Comment by SAIMEN-SAMA** [comment]
我覺得想做得更大的話，可以嘗試加入別的播放源，然後在番劇詳情頁可以選擇使用什麼播放源，我自己也不懂編程，這是我一點小小的想法，我看有的相似類型的軟件，有這種功能
