### ISSUE TITLE
播放器莫名跳轉到其他番劇

### ISSUE THREAD

**Issue by ghost** [xioneko/neko-anime#17]
有時會出現這個問題，特別是播廣告的時候，當然不播廣告的時候也有觸發過一兩次，不確定觸發機制是什麼，這是應該發生的嗎？

**Comment by ghost** [comment]
我覺得我可能找到問題所在了，這個件十分容易誤觸，就算離那個地方有一段距離也會按到，例如在靠近的位置拖動進度條，而且不知道是出於什麼原因，按這個鍵並不會跳轉到第2集，我是直接跳到第2個番![IMG_20240425_131239.png](https://github.com/xioneko/neko-anime/assets/154971655/7d947241-0ba3-4c1a-b90e-d33221fdebe7)

**Comment by xioneko** [comment]
🥹 感谢反馈，视频播放的这块代码比较乱，可能有莫名其妙的 Bug，留着以后重构

**Comment by ghost** [comment]
> 🥹 感谢反馈，视频播放的这块代码比较乱，可能有莫名其妙的 Bug，留着以后重构

情況好像還挺嚴峻的，有的時候點擊屏幕中間的畫面，都有可能會跳轉到別的地方，淺淺催更（）

**Comment by xioneko** [comment]
五一假期来一波更新

**Comment by xioneko** [comment]
> > 🥹 感谢反馈，视频播放的这块代码比较乱，可能有莫名其妙的 Bug，留着以后重构
> 
> 情況好像還挺嚴峻的，有的時候點擊屏幕中間的畫面，都有可能會跳轉到別的地方，淺淺催更（）

[新版本](https://github.com/xioneko/neko-anime/releases/tag/v0.3.0) 已经发布了，如果还是遇到这种问题（排除误触的情况），欢迎反馈
