### ISSUE TITLE
Request to support Android 11

### ISSUE THREAD

**Issue by Lucky-069** [xioneko/neko-anime#2]
I have been on Android 11 and I'm sure there must be bunch of other android 11 users too.. It's sad to see that the app needs android 12+ if it's possible please add android 11 support to it.

**Comment by xioneko** [comment]
@Lucky-069, Android 11 is already supported in version 0.1.2. [Check the latest release](https://github.com/xioneko/neko-anime/releases/tag/v0.1.2)
Thanks for your suggestion!
