### ISSUE TITLE
一直显示数据源出问题，求解决

### ISSUE THREAD

**Issue by FHYLJOC** [xioneko/neko-anime#21]
一直显示数据源出问题，求解决

**Comment by xioneko** [comment]
😢 yhmgo 域名挂了

**Comment by xioneko** [comment]
> 😢 yhmgo 域名挂了

www.yhdmw.cc 可用

**Comment by FHYLJOC** [comment]
作者，大概什么时候APP能维修好，真的太爱这个APP了

**Comment by xioneko** [comment]
> 作者，大概什么时候APP能维修好，真的太爱这个APP了

暂且考虑直接更换数据源，最快明天能修复好

**Comment by xioneko** [comment]
还不清楚 www.yhmgo.com 网站会不会恢复，如果站长只是决定更换一个域名，那也比较容易解决

否则，只能考虑切换到一个全新的樱花动漫数据源了，这样的话 **原先的追番列表、观看记录都会失效**，番剧数据缓存也会失效，有点可怕😣

目前还是先观望一段时间吧，对不住了🥹

**Comment by FHYLJOC** [comment]
其他网站广告弹窗太多了，真的看不动了，求作者决定维修app🥹🥹🥹不用怕记录

**Comment by xioneko** [comment]
谢谢支持！这几天我抽时间弄一弄，如果顺利的话可以先出一个预发布版本，最晚月底出正式版

**Comment by xioneko** [comment]
@FHYLJOC 新版本已发布 :D，见 [v0.4.0](https://github.com/xioneko/neko-anime/releases/tag/v0.4.0)
