### ISSUE TITLE
下載功能還沒好嗎

### ISSUE THREAD

**Issue by ghost** [xioneko/neko-anime#23]

**Comment by xioneko** [comment]
🫠这个月弄一弄，顺便修复一些小 Bug

**Comment by xioneko** [comment]
🎉 新版已发布 [v0.5.0](https://github.com/xioneko/neko-anime/releases/tag/v0.5.0)，有问题欢迎 reopen

点击播放器右上角三点按钮展开菜单，就能看到下载按钮了
