### ISSUE TITLE
作者你好，有几个问题能拜托你修复吗：
-视频加载速度有点慢，是否还能加快
-有些番剧总集数过多（>100），是否能多做几个按键方便观看想要的集数

希望下载到本地存储功能实现

### ISSUE THREAD

**Issue by mdskirito** [xioneko/neko-anime#24]

**Comment by xioneko** [comment]
视频加载速度跟动漫数据源的质量以及网络环境有关，App 没法直接控制

番剧集数过多，确实需要多划几下，看看这样优化会不会好一点：
进入播放页面时，直接滚动到上一次观看的集数，这样一集集看就不需要每次都划很多下了

下载功能会安排在下一个版本，敬请期待^_^

**Comment by mdskirito** [comment]
感觉可行，或对一定数量集数进行分格，如1-100一个按键，201-300一个按键…，然后点按键，他就会显示该范围的集数

好期待新版本噢，大概几时会推出

**Comment by xioneko** [comment]
预计八月底到九月初

**Comment by xioneko** [comment]
> 预计八月底到九月初

(๑•̀ㅂ•́)و✧ 正在努力开发中……

**Comment by xioneko** [comment]
🎉 新版已发布 [v0.5.0](https://github.com/xioneko/neko-anime/releases/tag/v0.5.0)，有问题欢迎 reopen

点击播放器右上角三点按钮展开菜单，就能看到下载按钮了
