### ISSUE TITLE
Feature Request for Neko Anime App 

### ISSUE THREAD

**Issue by HalfBloodprinc3** [xioneko/neko-anime#31]
Hello sir,

I know this is kind of disrespectful for demanding something like this again but I show your app to many of my friends and they really appreciate it. But there is only one problem, the language for both the app and the content.

If you release a translated version of this app and just add the **gogoanime** source in your app the it would be great for all those persons who liked your app but can't use it because of these restrictions.

I don't want to sound rude and I am not pressurising you for anything.

 I,  sorry, we just want to use your app .

**Comment by xioneko** [comment]
Sorry, there are currently no plans to support this. 

There are two considerations: First, developing new features for the app takes a lot of time, and to ensure a good user experience, I have to focus on a small number of features for now. Second, anime sources may involve copyright issues, so it might be better to access these anime source websites directly. 

Anyway, thanks for your suggestions.
