### ISSUE TITLE
Request to available it globally 

### ISSUE THREAD

**Issue by HalfBloodprinc3** [xioneko/neko-anime#5]
I liked the app ui and the overall experience of this app was great. But I can't use it in India. So if there is any possibility of releasing a global version of this app which supports every possible region with active streaming and download service then it would be a great help for us weebs.

**Comment by xioneko** [comment]
Thanks, but it might not be possible for me to do that. The biggest problem is not about writing the code, but getting the anime resources. The app is just a third-party client, and all the anime resources it uses come from the Internet. Finding free resources in other languages would be quite time consuming and difficult work. So... sorry.

**Comment by HalfBloodprinc3** [comment]
Ooh... it's ok.I understand.
But if someday you can make it possible...then let me know 😅.
Btw...If you need free resources..then I can help. And there is a app called "Saikou Beta" , available on github, it uses the free resources for global region. I am not forcing you for anything. I'm just trying to help you.

Btw... thanks for the response 😀. And keep it up. This app is great 👍.
