### ISSUE TITLE
请求支持 Android 10

### ISSUE THREAD

**Issue by amokiel** [xioneko/neko-anime#6]
在平板上体验挺不错的！希望开发者可以考虑支持Android 10，多谢！

**Comment by xioneko** [comment]
(oﾟ▽ﾟ)o  说实话，我还真没在平板上做过测试，或许以后可以优化一下平板适配，Android 10 的支持应该可以

**Comment by amokiel** [comment]
> (oﾟ▽ﾟ)o 说实话，我还真没在平板上做过测试，或许以后可以优化一下平板适配，Android 10 的支持应该可以

感谢回复，开发者辛苦啦!

**Comment by xioneko** [comment]
@amokiel    \\^o^/

🎉 新版本 [v0.2.1](https://github.com/xioneko/neko-anime/releases/tag/v0.2.1) 已发布，📝[更新日志](https://github.com/xioneko/neko-anime#v021-2023-9-17)
