### ISSUE TITLE
关于在折叠屏手机上的显示问题

### ISSUE THREAD

**Issue by NuoL5623** [xioneko/neko-anime#7]
也不太确定是什么原因造成的，可能是大屏幕的显示比例？首页图片滚动显示的时候右边会有很大的一大片的空白
还有仅仅是个人的使用体验 程序能够增加自动旋转就好啦 手机需要翻来覆去的转稍微有点儿麻烦呐
非常感谢！！

**Comment by xioneko** [comment]
感谢反馈 (●'◡'●) ！我之前也发现了这个问题，九月份我会抽空改善一下 UI

**Comment by NuoL5623** [comment]
还有这两天用下来发现的，不知道是不是我的设置问题，全屏播放之后旋转手机会退出全屏播放；
搜索界面进行搜索之后有时候会突然闪退；
有空的 也麻烦你一并测试下吧，非常感谢!!

**Comment by xioneko** [comment]
闪退发生时，是否已经显示了部分搜索结果？是搜索特定的关键词时发生的吗？
旋转的问题是不是，在开启手机的“自动旋转”功能后，在竖屏状态下，手动切换到全屏模式，然后再旋转屏幕，发现全屏模式临时退出了一下。

**Comment by NuoL5623** [comment]
没有发现闪退的关键词有什么关联性，闪退发生的时候已经显示了部分内容了，不过好像都是发生在网络信号不太好的情况下
旋转的问题跟你的描述基本一致，手动切换到全屏模式之后，竖屏状态下会临时退出全屏，横屏之后又恢复了全屏

**Comment by xioneko** [comment]
了解了( •̀ .̫ •́ )✧

**Comment by xioneko** [comment]
@NuoL5623    \\^o^/

🎉 新版本 [v0.2.1](https://github.com/xioneko/neko-anime/releases/tag/v0.2.1) 已发布，📝[更新日志](https://github.com/xioneko/neko-anime#v021-2023-9-17)

**Comment by NuoL5623** [comment]
之前的问题全都修复了，非常感谢！
期待后续关于视频缓存功能的更新啦
不知道是不是网站和网络问题总觉得在线播放非常容易卡顿
还有就是关于视频的清晰度不知道有没有办法能够提高了
https://github.com/670848654/SakuraAnime 个人感觉这位的app也是有一些不错的地方当然也有一些不太满意的地方，供参考
再次感谢聆听

**Comment by xioneko** [comment]
跟一些大佬的项目相比确实还有些差距，以后一点点改进
