### ISSUE TITLE
您好，您可以添加质量选项和英文字幕吗？我来自另一个国家，我真的很喜欢这个应用程序，但我无法理解应用程序中的任何内容，我使用翻译来发送此内容，我求求你了。

### ISSUE THREAD

**Issue by buttlicker2** [xioneko/neko-anime#8]
您好，您可以添加质量选项和英文字幕吗？我来自另一个国家，我真的很喜欢这个应用程序，但我无法理解应用程序中的任何内容，我使用翻译来发送此内容，我求求你了。

**Comment by xioneko** [comment]
感谢建议，但是考虑到我的个人精力有限┐(´∀｀)┌ ，目前没有国际化的打算，你可以考虑一下 GitHub 其他优秀的支持英文的动漫应用。
